name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract changelog for tag
        id: changelog
        run: |
          tag_name=${GITHUB_REF#refs/tags/}
          awk "/## \[$tag_name\]/,/^## \[/" CHANGELOG.md | sed '$d' > RELEASE_BODY.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
        #   draft: false  自动发布
        #   prerelease: false  # 自动发布
          body_path: RELEASE_BODY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
