name: Create Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract changelog for tag
        id: changelog
        run: |
          tag_name=${GITHUB_REF#refs/tags/}
          awk -v tag="$tag_name" '
            /^## \[/ && $0 ~ "\\[" tag "\\]" {
              in_section = 1
              next
            }
            /^## \[/ && in_section {
              exit
            }
            in_section {
              print
            }
          ' CHANGELOG.md > RELEASE_BODY.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
        #   draft: false  自动发布
        #   prerelease: false  # 自动发布
          body_path: RELEASE_BODY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
